export let Users = [
  { name: "Rahul" },
  { name: "Amit" },
  { name: "Priya" },
  { name: "Anjali" },
  { name: "Vikram" },
  { name: "Neha" },
  { name: "Raj" },
  { name: "Kiran" },
  { name: "Sanjay" },
  { name: "Pooja" },
  { name: "Deepak" },
  { name: "Sunita" },
  { name: "Arjun" },
  { name: "Meera" },
  { name: "Vinay" },
  { name: "Kavita" },
  { name: "Ravi" },
  { name: "Swati" },
  { name: "Manoj" },
];
